#!/bin/bash

# ============================================================
#  N E T   W R I A T H  (v4.7 Multi-Target Edition)
# ============================================================

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
GRAY='\033[0;90m'
NC='\033[0m' # No Color

# --- Variables ---
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_BASE="$PROJECT_DIR/outputs"

# --- Helper Functions ---

check_dependencies() {
    for tool in subfinder dnsx httpx naabu; do
        if ! command -v $tool &> /dev/null; then
            echo -e "${YELLOW}[!] Dependency Missing: $tool${NC}"
            exit 1
        fi
    done
}

setup_target() {
    TARGET_DOMAIN=$1
    TARGET_DIR="$OUTPUT_BASE/$TARGET_DOMAIN"
    REPORT_FILE="$TARGET_DIR/Final_Report.md"
    TEMP_DIR="$TARGET_DIR/tmp"

    if [ -d "$TARGET_DIR" ]; then
        echo -e "\n${YELLOW}[!] Overlap Detected For $TARGET_DOMAIN.${NC}"
        echo -ne "    ${WHITE}Purge Existing? (Y/N): ${NC}"
        read choice
        if [[ "$choice" == "y" || "$choice" == "Y" ]]; then
            rm -rf "$TARGET_DIR"
        fi
    fi

    mkdir -p "$TARGET_DIR" "$TEMP_DIR"
}

run_mission() {
    echo -e "\n${RED}Init:: Stealth Recon On ${WHITE}$TARGET_DOMAIN${NC}"
    
    # 1. Subdomains
    echo -ne "${YELLOW}[*] Phase 1: Subdomain Discovery...  ${NC}"
    echo "$TARGET_DOMAIN" > "$TEMP_DIR/subs.txt"
    subfinder -d "$TARGET_DOMAIN" -silent >> "$TEMP_DIR/subs.txt" 2>/dev/null
    sort -u "$TEMP_DIR/subs.txt" -o "$TEMP_DIR/subs.txt"
    echo -e "${GREEN}Success${NC}"

    # 2. Comprehensive IP Resolution
    echo -ne "${YELLOW}[*] Phase 2: Comprehensive IP Resolution... ${NC}"
    # Resolve all subdomains to [ip]
    dnsx -l "$TEMP_DIR/subs.txt" -a -resp -nc -silent > "$TEMP_DIR/resolved_raw.txt" 2>/dev/null
    
    # Process into clean domain/ip list
    > "$TEMP_DIR/resolved_clean.txt"
    while read -r line; do
        domain=$(echo "$line" | awk '{print $1}')
        ip=$(echo "$line" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | head -n 1)
        if [ ! -z "$ip" ]; then
            echo "$domain/$ip" >> "$TEMP_DIR/resolved_clean.txt"
        fi
    done < "$TEMP_DIR/resolved_raw.txt"
    
    # Extract unique IPs for port scanning
    grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" "$TEMP_DIR/resolved_clean.txt" | sort -u > "$TEMP_DIR/unique_ips.txt"
    
    echo -e "${GREEN}Success${NC}"

    # 3. Live Web Filtering
    echo -ne "${YELLOW}[*] Phase 3: Live Web Filtering...  ${NC}"
    httpx -l "$TEMP_DIR/subs.txt" -silent -o "$TEMP_DIR/live.txt" >/dev/null 2>&1
    echo -e "${GREEN}Success${NC}"

    # 4. Surgical Port Scanning (Per Unique IP)
    echo -ne "${YELLOW}[*] Phase 4: Multi-Target Port Scanning...  ${NC}"
    mkdir -p "$TEMP_DIR/port_results"
    if [ -s "$TEMP_DIR/unique_ips.txt" ]; then
        while read -r ip; do
            naabu -host "$ip" -top-ports 100 -silent -o "$TEMP_DIR/port_results/$ip.txt" >/dev/null 2>&1
        done < "$TEMP_DIR/unique_ips.txt"
    else
        echo -e "${RED}Skipped (No IPs resolved)${NC}"
    fi
    echo -e "${GREEN}Success${NC}"

    # 5. Data Synthesis & Reporting
    echo -ne "${YELLOW}[*] Phase 5: Synthesis & Reporting...  ${NC}"
    {
        echo "# NetWriath Recon Report: $TARGET_DOMAIN"
        echo -e "\n**Date:** $(date)"
        
        echo -e "\n## 🌐 Phase 1: Discovered Hostnames"
        if [ -s "$TEMP_DIR/subs.txt" ]; then
            cat "$TEMP_DIR/subs.txt" | awk '{print "- " $1}'
        else
            echo "No subdomains discovered."
        fi

        echo -e "\n## 📍 Phase 2: Asset Inventory (Domain/IP)"
        echo "| Hostname | IP Address |"
        echo "| --- | --- |"
        if [ -s "$TEMP_DIR/resolved_clean.txt" ]; then
            while read -r line; do
                echo "| $(echo "$line" | cut -d/ -f1) | $(echo "$line" | cut -d/ -f2) |"
            done < "$TEMP_DIR/resolved_clean.txt"
        else
            echo "| None | None |"
        fi
        
        echo -e "\n## ⚡ Phase 3: Active Web Services"
        if [ -s "$TEMP_DIR/live.txt" ]; then
            cat "$TEMP_DIR/live.txt" | awk '{print "- " $1}'
        else
            echo "No active web servers detected."
        fi
        
        echo -e "\n## 🔓 Phase 4: Port Inventory (By IP Address)"
        if [ "$(ls -A "$TEMP_DIR/port_results" 2>/dev/null)" ]; then
            for ip_file in "$TEMP_DIR/port_results"/*.txt; do
                ip_addr=$(basename "$ip_file" .txt)
                if [ -s "$ip_file" ]; then
                    echo -e "\n### Host: $ip_addr"
                    echo "| Port | Status |"
                    echo "| --- | --- |"
                    cat "$ip_file" | cut -d: -f2 | awk '{print "| " $1 " | Open |"}'
                fi
            done
        else
            echo "No open ports discovered across infrastructure."
        fi
        
        echo -e "\n---\n*Generated by NetWriath 👻*"
    } > "$REPORT_FILE"
    
    rm -rf "$TEMP_DIR"
    echo -e "${GREEN}Success${NC}"
    echo -e "\n${GREEN}[+] Mission Complete: $REPORT_FILE${NC}"
}

# --- ELITE TERMINAL UI ---

while true; do
    clear
    echo -e "${RED} ███╗   ██╗███████╗████████╗██╗    ██╗██████╗ ██╗ █████╗ ████████╗██╗  ██╗"
    echo -e " ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔══██╗██║██╔══██╗╚══██╔══╝██║  ██║"
    echo -e " ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██████╔╝██║███████║   ██║   ███████║"
    echo -e " ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██╔══██╗██║██╔══██║   ██║   ██║  ██║"
    echo -e " ██║ ╚████║███████╗   ██║   ╚███╔███╔╝██║  ██║██║██║  ██║   ██║   ██║  ██║"
    echo -e " ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝${NC}"
    echo -e " ${WHITE} Automated Asset Discovery Framework // v4.7${NC}"
    echo -e ""
    echo -e " ${RED}--------------------------------------------------------------------------${NC}"
    echo -e " ${WHITE}:: [1] Deploy Mission${NC}"
    echo -e " ${WHITE}:: [2] Purge Database${NC}"
    echo -e " ${RED}:: [3] Disconnect${NC}"
    echo -e " ${RED}--------------------------------------------------------------------------${NC}"
    echo ""
    echo -ne " ${WHITE}Option > ${NC}"
    read OPTION

    case $OPTION in
        1)
            echo ""
            echo -ne " ${WHITE}Target > ${NC}"
            read TARGET
            [ -z "$TARGET" ] && continue
            setup_target "$TARGET"
            run_mission
            echo ""
            echo -ne " ${WHITE}Press Enter To Return...${NC}"
            read
            ;;
        2)
            echo -e "\n ${YELLOW}[!] Purging Local Database...${NC}"
            rm -rf "$OUTPUT_BASE"/*
            sleep 1
            echo -e " ${YELLOW}[+] Purge Successful${NC}"
            sleep 1
            ;;
        3)
            echo -e "\n ${YELLOW}[*] Disconnecting From Mainframe...${NC}"
            exit 0
            ;;
        *)
            echo -e "\n ${YELLOW}[!] Unknown Command${NC}"
            sleep 1
            ;;
    esac
done
