#!/bin/bash

# ============================================================
#  N E T   W R I A T H  (v4.6 Strategic Edition)
# ============================================================

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
GRAY='\033[0;90m'
NC='\033[0m' # No Color

# --- Variables ---
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_BASE="$PROJECT_DIR/outputs"

# --- Helper Functions ---

check_dependencies() {
    for tool in subfinder dnsx httpx naabu; do
        if ! command -v $tool &> /dev/null; then
            echo -e "${YELLOW}[!] Dependency Missing: $tool${NC}"
            exit 1
        fi
    done
}

setup_target() {
    TARGET_DOMAIN=$1
    TARGET_DIR="$OUTPUT_BASE/$TARGET_DOMAIN"
    REPORT_FILE="$TARGET_DIR/Final_Report.md"
    TEMP_DIR="$TARGET_DIR/tmp"

    if [ -d "$TARGET_DIR" ]; then
        echo -e "\n${YELLOW}[!] Overlap Detected For $TARGET_DOMAIN.${NC}"
        echo -ne "    ${WHITE}Purge Existing? (Y/N): ${NC}"
        read choice
        if [[ "$choice" == "y" || "$choice" == "Y" ]]; then
            rm -rf "$TARGET_DIR"
        fi
    fi

    mkdir -p "$TARGET_DIR" "$TEMP_DIR"
}

run_mission() {
    echo -e "\n${RED}Init:: Stealth Recon On ${WHITE}$TARGET_DOMAIN${NC}"
    
    # 1. Subdomains
    echo -ne "${YELLOW}[*] Phase 1: Subdomain Discovery...  ${NC}"
    echo "$TARGET_DOMAIN" > "$TEMP_DIR/subs.txt"
    subfinder -d "$TARGET_DOMAIN" -silent >> "$TEMP_DIR/subs.txt" 2>/dev/null
    sort -u "$TEMP_DIR/subs.txt" -o "$TEMP_DIR/subs.txt"
    echo -e "${GREEN}Success${NC}"

    # 2. Primary IP Resolution
    echo -ne "${YELLOW}[*] Phase 2: Primary IP Resolution... ${NC}"
    # Resolve specifically the main domain
    PRIMARY_IP=$(echo "$TARGET_DOMAIN" | dnsx -a -resp-only -nc -silent | head -n 1)
    if [ -z "$PRIMARY_IP" ]; then
        PRIMARY_IP="Resolution Failed"
    fi
    echo -e "${GREEN}Success${NC}"

    # 3. Live Web Filtering
    echo -ne "${YELLOW}[*] Phase 3: Live Web Filtering...  ${NC}"
    httpx -l "$TEMP_DIR/subs.txt" -silent -o "$TEMP_DIR/live.txt" >/dev/null 2>&1
    echo -e "${GREEN}Success${NC}"

    # 4. Infrastructure Port Scan
    echo -ne "${YELLOW}[*] Phase 4: Server Port Scanning...  ${NC}"
    if [[ "$PRIMARY_IP" != "Resolution Failed" ]]; then
        naabu -host "$PRIMARY_IP" -top-ports 100 -silent -o "$TEMP_DIR/ports.txt" >/dev/null 2>&1
    else
        echo -e "${RED}Skipped (No IP)${NC}"
    fi
    echo -e "${GREEN}Success${NC}"

    # 5. Data Synthesis & Reporting
    echo -ne "${YELLOW}[*] Phase 5: Synthesis & Reporting...  ${NC}"
    {
        echo "# NetWriath Recon Report: $TARGET_DOMAIN"
        echo -e "\n**Date:** $(date)"
        
        echo -e "\n## 🌐 Phase 1: Discovered Hostnames"
        if [ -s "$TEMP_DIR/subs.txt" ]; then
            cat "$TEMP_DIR/subs.txt" | awk '{print "- " $1}'
        else
            echo "No subdomains discovered."
        fi

        echo -e "\n## 📍 Phase 2: Primary Infrastructure"
        echo "**Main Server IP:** $PRIMARY_IP"
        
        echo -e "\n## ⚡ Phase 3: Active Web Services"
        if [ -s "$TEMP_DIR/live.txt" ]; then
            cat "$TEMP_DIR/live.txt" | awk '{print "- " $1}'
        else
            echo "No active web servers detected."
        fi
        
        echo -e "\n## 🔓 Phase 4: Server Port Inventory"
        echo "**Target IP:** $PRIMARY_IP"
        echo ""
        echo "| Port | Status |"
        echo "| --- | --- |"
        if [ -s "$TEMP_DIR/ports.txt" ]; then
            cat "$TEMP_DIR/ports.txt" | cut -d: -f2 | awk '{print "| " $1 " | Open |"}'
        else
            echo "| None Detected | N/A |"
        fi
        
        echo -e "\n---\n*Generated by NetWriath 👻*"
    } > "$REPORT_FILE"
    
    rm -rf "$TEMP_DIR"
    echo -e "${GREEN}Success${NC}"
    echo -e "\n${GREEN}[+] Mission Complete: $REPORT_FILE${NC}"
}

# --- ELITE TERMINAL UI ---

while true; do
    clear
    echo -e "${RED} ███╗   ██╗███████╗████████╗██╗    ██╗██████╗ ██╗ █████╗ ████████╗██╗  ██╗"
    echo -e " ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔══██╗██║██╔══██╗╚══██╔══╝██║  ██║"
    echo -e " ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██████╔╝██║███████║   ██║   ███████║"
    echo -e " ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██╔══██╗██║██╔══██║   ██║   ██║  ██║"
    echo -e " ██║ ╚████║███████╗   ██║   ╚███╔███╔╝██║  ██║██║██║  ██║   ██║   ██║  ██║"
    echo -e " ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝${NC}"
    echo -e " ${WHITE} Automated Asset Discovery Framework // v4.6${NC}"
    echo -e ""
    echo -e " ${RED}--------------------------------------------------------------------------${NC}"
    echo -e " ${WHITE}:: [1] Deploy Mission${NC}"
    echo -e " ${WHITE}:: [2] Purge Database${NC}"
    echo -e " ${RED}:: [3] Disconnect${NC}"
    echo -e " ${RED}--------------------------------------------------------------------------${NC}"
    echo ""
    echo -ne " ${WHITE}Option > ${NC}"
    read OPTION

    case $OPTION in
        1)
            echo ""
            echo -ne " ${WHITE}Target > ${NC}"
            read TARGET
            [ -z "$TARGET" ] && continue
            setup_target "$TARGET"
            run_mission
            echo ""
            echo -ne " ${WHITE}Press Enter To Return...${NC}"
            read
            ;;
        2)
            echo -e "\n ${YELLOW}[!] Purging Local Database...${NC}"
            rm -rf "$OUTPUT_BASE"/*
            sleep 1
            echo -e " ${YELLOW}[+] Purge Successful${NC}"
            sleep 1
            ;;
        3)
            echo -e "\n ${YELLOW}[*] Disconnecting From Mainframe...${NC}"
            exit 0
            ;;
        *)
            echo -e "\n ${YELLOW}[!] Unknown Command${NC}"
            sleep 1
            ;;
    esac
done
